# cirrus.yml
task:
  build:
    # Define the OS image to be built
    container:
      image: 'ubuntu:20.04'
    environment:
      - BRANCH: lineage-23.1
      - DEVICE: rodin
      - ROM: LineageOS
      - AOSP: true
    install:
      # Install necessary dependencies
      - sudo apt update && sudo apt install -y repo git gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev lib32z1-dev lib32readline-dev lib32sqlite3-dev lib32freetype6-dev lib32gcc1 lib32stdc++6 lib32ncursesw5-dev lib32bz2-dev liblz4-tool
    pre_build:
      # Set up repo and clone the sources
      - git clone https://github.com/mt6899-rodin/android_device_xiaomi_rodin -b lineage-23.1 device/xiaomi/rodin
      - mkdir -p ~/.repo/manifests
      - curl https://raw.githubusercontent.com/LineageOS/android_manifest/lineage-23.1/default.xml -o ~/.repo/manifests/default.xml
      - repo init -u https://github.com/LineageOS/android.git -b $BRANCH
      - repo sync -j4
    build:
      # Start building the ROM
      - source build/envsetup.sh
      - lunch lineage_rodin-userdebug
      - mka bacon
    post_build:
      # Upload the build result to artifact storage or your preferred location
      - curl -F "file=@out/target/product/rodin/lineage-23.1-*.zip" https://ci.example.com/upload
