env:
  TWRP_SYNC: https://github.com/extremerom/platform_manifest_twrp.git
  TWRP_BRANCH: twrp-14
  DT_REPO: https://github.com/TegarXLu/Recovery-Rodin-Rebase.git
  DT_BRANCH: Twrp
  DT_PATH: device/xiaomi/rodin
  DEVICE_MAKEFILE: twrp_rodin-ap2a
  DEVICE_NAME: rodin
  BUILD_TARGET: vendorboot
  TIMEZONE: Asia/lampung
  RELEASE_REPO: TegarXLu/Recovery-Release
  GH_TOKEN: ENCRYPTED[!44d242237d643d0b3167f9ed5c29de9c91d4c6f47a6049eaee5d5938be15d12b734a70be11cba488b039df58024e8581!]
  
task:
  name: "Build Twrp"
  timeout_in: 480m
  container:
    image: eraselk/ubuntu:22.04
    cpu: 8
    memory: 32G

  script:
    - chmod a+x *.sh
    - ./build.sh
    - exit $?
