# Example Cirrus CI configuration for building LineageOS recovery for Poco X7 Pro

# Define the build configuration
task:
  name: Build LineageOS Recovery for Poco X7 Pro Rodin
  docker:
    image: ubuntu:20.04  # Using Ubuntu 20.04 as base image
    privileged: true  # Grant privileged mode for building recovery

  environment:
    ANDROID_BUILD_TOP: $HOME/android
    TARGET_DEVICE: "rodin"  # Poco X7 Pro Rodin's device codename
    RECOVERY_VARIANT: "recovery"  # Recovery build type
    OUTPUT_DIR: $HOME/output
    BRANCH: "lineage-18.1"  # Specify the LineageOS branch you want to use

  # Define the steps to be executed
  script:
    - git clone https://github.com/LineageOS/android.git $ANDROID_BUILD_TOP
    - cd $ANDROID_BUILD_TOP
    - git checkout $BRANCH
    - source build/envsetup.sh
    - lunch lineage_rodin-userdebug  # Set the build environment for your device
    - make recoveryimage  # Build the recovery image
    - mkdir -p $OUTPUT_DIR
    - cp $ANDROID_BUILD_TOP/out/target/product/rodin/recovery.img $OUTPUT_DIR/

  # After build, upload the recovery image to the artifacts for download
  artifacts:
    - $OUTPUT_DIR/recovery.img

# This will allow you to trigger builds automatically in Cirrus CI when you push changes to the repo
