env:
  FOX_SYNC: https://github.com/PitchBlackRecoveryProject/manifest_pb
  FOX_BRANCH: android-14.0
  DT_REPO: https://github.com/linastorvaldz/recovery_xiaomi_gold.git
  DT_BRANCH: HOS2-14.1
  DT_PATH: device/xiaomi/gold
  DEVICE_MAKEFILE: twrp_gold-ap2a
  DEVICE_NAME: gold
  BUILD_TARGET: vendorboot
  TIMEZONE: Asia/lampung
  RELEASE_REPO: TegarXLu/Recovery-Release
  GH_TOKEN: ENCRYPTED[!44d242237d643d0b3167f9ed5c29de9c91d4c6f47a6049eaee5d5938be15d12b734a70be11cba488b039df58024e8581!]

task:
  name: "Build Fox"
  timeout_in: 480m
  container:
    image: eraselk/ubuntu:22.04
    cpu: 8
    memory: 32G

  script:
    - chmod a+x *.sh
    - ./build.sh
    - exit $?
