task:
  build:
    container:
      image: "circleci/python:3.8"
      shell: /bin/bash
    script:
      - git clone --depth 1 https://github.com/LineageOS/android.git -b lineage-23.1
      - cd android
      - git clone --depth 1 https://github.com/mt6899-rodin/android_device_xiaomi_rodin -b lineage-23.1 device/xiaomi/rodin
      - git clone --depth 1 https://github.com/SenX-Project/vendor_xiaomi_rodin -b lineage-23.1 vendor/xiaomi/rodin
      - git clone --depth 1 https://github.com/mt6899-rodin/android_device_xiaomi_rodin-kernel -b lineage-23.1 kernel/xiaomi/rodin
      - repo sync --force-sync
      - source build/envsetup.sh
      - lunch lineage_rodin-userdebug
      - mka bacon
